<?php

namespace ZnBundle\Log\Domain\Services;

use ZnBundle\Log\Domain\Entities\HistoryEntity;
use ZnBundle\Log\Domain\Entities\LogEntity;
use ZnBundle\Log\Domain\Interfaces\Repositories\HistoryRepositoryInterface;
use ZnBundle\Log\Domain\Interfaces\Services\HistoryServiceInterface;
use ZnCore\Domain\Service\Base\BaseCrudService;
use ZnCore\Domain\EntityManager\Interfaces\EntityManagerInterface;
use ZnCore\Domain\DataProvider\Libs\DataProvider;
use ZnCore\Domain\Query\Entities\Query;

class HistoryService extends BaseCrudService implements HistoryServiceInterface
{

    public function __construct(EntityManagerInterface $em, HistoryRepositoryInterface $historyRepository)
    {
        $this->setEntityManager($em);
        $this->setRepository($historyRepository);
    }

    public function getEntityClass(): string
    {
        return HistoryEntity::class;
    }

    public function getDataProvider(Query $query = null): DataProvider
    {
        return parent::getDataProvider($query); // TODO: Change the autogenerated stub
    }
}
